ALIGNMENT_TOWN = 0
ALIGNMENT_MAFIA = 1
ALIGNMENT_WEREWOLVES = 2
ALIGNMENT_SERIAL_KILLER = 3

STAGE_DAY = 0
STAGE_TWILIGHT = 1
STAGE_NIGHT = 2
STAGE_DAWN = 3

STAGE_LENGTH_DAY = 300
STAGE_LENGTH_TWILIGHT = 5
STAGE_LENGTH_NIGHT = 30
STAGE_LENGTH_DAWN = 5
DAYBREAK_EVENT_TIME = 3

ACTION_TYPE_EXAMPLE = 0
ACTION_TYPE_KILL = 1
ACTION_TYPE_PROTECT = 2
ACTION_TYPE_INVESTIGATE = 3
ACTION_TYPE_BLOCK = 4

RESOLUTION_TYPE_RESULT = 1
RESOLUTION_TYPE_EVENT = 2
RESOLUTION_TYPE_RESULT_WITH_CALLBACK = 3
RESOLUTION_TYPE_SILENT = 4